# Generated by Django 3.2.3 on 2022-06-20 08:23

import ApiMedico.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='estado',
            field=models.CharField(max_length=20, validators=[ApiMedico.utils.validador_pendiente_entregado]),
        ),
    ]
